import { IHome } from "./types";

export const homeLists: IHome[] = [
  {
    id: "1",
    name: "Text 1",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: true,
    tag: "omg",
  },
  {
    id: "2",
    name: "Text 2",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: false,
    tag: "lol",
  },
  {
    id: "3",
    name: "Text 1",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: true,
    tag: "omg",
  },
  {
    id: "4",
    name: "Text 2",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: false,
    tag: "lol",
  },
  {
    id: "5",
    name: "Text 1",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: true,
    tag: "omg",
  },
  {
    id: "6",
    name: "Text 2",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: false,
    tag: "lol",
  },
  {
    id: "7",
    name: "Text 1",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: true,
    tag: "omg",
  },
  {
    id: "8",
    name: "Text 2",
    cost: "",
    images: [
      "https://i.ibb.co/ncrXc2V/1.png",
      "https://i.ibb.co/B3s7v4h/2.png",
      "https://i.ibb.co/XXR8kzF/3.png",
    ],
    availableDate: "",
    average: 5,
    liked: false,
    tag: "lol",
  },
];
